import Head from "next/head";
import Image from "next/image";
import styles from "../styles/LandingPage/Home.module.css";
import styled from "@emotion/styled";
import { darkTheme } from "../theme/themes";
import { TypeAnimation } from "react-type-animation";
import { Button } from "@mui/material";
import { Values } from "../components/LandingPage/Values";

import { Header } from "../components/LandingPage/Header";
import { Products } from "../components/LandingPage/Products";
import { Testimonials } from "../components/LandingPage/Testimonials";

const ImageAndInfoDiv = styled("div")`
  display: flex;
  flex-direction: column;
  text-align: center;
  flex-wrap: wrap;
  justify-content: center;
  align-items: center;
`;

const InfoContainer = styled("div")`
  display: flex;
  flex-direction: column;
  justify-content: space-around;
  width: 100vw;
  text-align: left;
  align-items: center;
`;

const StyledParagh = styled("p")`
  font-size: calc(0.75vh + 0.75vw);
  line-height: 1.5;
  margin-bottom: 2rem;
  text-align: center;
  text-justify: inter-word;
  margin-top: 20px;
  margin-left: 10vw;
  margin-right: 10vw;
`;

const SnowRobotImage = styled(Image)`
  margin-left: 30px;
  margin-right: 30px;
  box-shadow: 0px 2px 6px rgba(0, 0, 0, 0.15);
  filter: grayscale(50%);
  transition: all 0.3s ease;
  border: 2px solid white;
  border-radius: 10px;
  height: 180px;
  width: 270px;
  margin-bottom: 30px;
  margin-top: 50px;

  &:hover {
    filter: grayscale(0%);
    transform: translateY(-5px);
    box-shadow: 0px 8px 12px rgba(0, 0, 0, 0.25);
    border: 2px solid ${darkTheme.primaryColor};
  }
`;

const BuyNowButton = styled(Button)`
  position: relative;
  border-radius: 20px;
  text-transform: none;
  width: 100px;
  color: ${darkTheme.primaryColor};
`;

const LandingDiv = styled("div")`
  height: 100vh;
  width: 100vw;
  display: flex;
  flex: 1;
  justify-content: center;
  text-align: center;
  flex-direction: column;
  align-items: center;
  margin-top: 30px;
`;

const LandingHeader = styled("p")`
  font-size: calc(2vw + 1.5vh);
  width: 50vw;
  justify-content: center;
  span {
    color: ${darkTheme.primaryColor04};
  }
`;

const ContactUsButton = styled(Button)`
  color: ${darkTheme.primaryColor};
  border-color: ${darkTheme.primaryColor};
  font-size: 16px;
  font-weight: 500;
  text-transform: none;
  letter-spacing: 1px;
  transition: all 0.2s ease-in-out;

  &:hover {
    background-color: transparent;
  }
`;

const CustomSubtitle = styled("p")`
  color: #949494;
`;

const ExploreProductsButtonDiv = styled("div")`
  display: flex;
  flex: 1;
  align-items: center;
  justify-content: center;
`;

const ExploreProductsButton = styled(Button)`
  display: inline-block;
  position: relative;
  z-index: 0;
  whitespace: no-wrap;
  color: ${darkTheme.primaryColor};
  font-family: "Open Sans";
  width: 300px;
  height: 50px;

  ::before {
    content: "";
    position: absolute;
    top: -2px;
    left: -2px;
    z-index: -1;
    filter: blur(4px);
    width: calc(100% + 3px);
    height: calc(100% + 3px);
    opacity: 1;
    background-image: linear-gradient(
      45deg,
      #ffffff,
      ${darkTheme.primaryColor},
      ${darkTheme.primaryColor02},
      ${darkTheme.primaryColor03},
      ${darkTheme.primaryColor04},
      ${darkTheme.primaryColor05}
    );
    animation: coolgradient 10s linear 0s infinite alternate;
    transition: opacity 0.3s ease-in-out 0s;

    @keyframes coolgradient {
      from {
        background-position: -250px 0;
      }
      to {
        background-position: 250px 0;
      }
    }
  }

  ::after {
    z-index: -1;
    content: "";
    position: absolute;
    width: 100%;
    height: 100%;
    background: rgb(17, 17, 17);
    left: 0px;
    top: 0px;
  }
`;

export default function Home() {
  return (
    <div className={styles.mainContainer}>
      <Head>
        <title>Snowbotics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Header />
        <LandingDiv>
          <LandingHeader>
            Unleash the <span>power</span> of high-performance snow blowers with{" "}
            <span>SnowBot.</span>
          </LandingHeader>
          <CustomSubtitle>
            No installations. Comes prepackaged with all features and more!
          </CustomSubtitle>
          <ExploreProductsButtonDiv>
            <ExploreProductsButton>Explore Products</ExploreProductsButton>
          </ExploreProductsButtonDiv>
        </LandingDiv>
      </div>
      <main className={styles.main}>
        <ImageAndInfoDiv>
          <InfoContainer>
            <TypeAnimation
              sequence={[
                "I am SnowBot",
                1000,
                "I am easy to use",
                1000,
                "I am smart",
                1000,
                "I require minimal maintenance",
                1000,
              ]}
              wrapper="span"
              cursor={true}
              repeat={Infinity}
              style={{
                fontSize: "calc(1.5vh + 1.5vw)",
                color: darkTheme.primaryColor02,
              }}
            />
            <SnowRobotImage
              src="/images/products/snowrobot.png"
              height={160}
              width={300}
              alt="Snow Plougher"
              style={{}}
            />
            <StyledParagh>
              Introducing our state-of-the-art snow clearing robot - the perfect
              solution for clearing snow from driveways, sidewalks, and other
              outdoor areas. Our robot is equipped with powerful brushes and a
              durable snow blower that can quickly and efficiently clear snow,
              even in the harshest winter conditions. With advanced sensors and
              smart navigation technology, our robot can navigate around
              obstacles and map out the most efficient snow clearing route. Say
              goodbye to backbreaking snow shoveling and let our snow clearing
              robot do the work for you!
            </StyledParagh>
            <BuyNowButton variant="outlined">Buy now</BuyNowButton>
          </InfoContainer>
        </ImageAndInfoDiv>
      </main>
      <Values />
      <Products />
      <Testimonials />
      <div className={styles.contactUsDiv}>
        <h1>Excited to get in touch? Come along!</h1>
        <ContactUsButton
          variant="outlined"
          size="large"
          sx={{ my: 2, display: "block" }}
        >
          Contact us
        </ContactUsButton>
      </div>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image
              src="/vercel.svg"
              alt="Vercel Logo"
              width={72}
              height={16}
              color="white"
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
